apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cicd-tools

# Deploy pre-configured SonarQube from Red Hat Canada demo catalog.
bases:
  - github.com/redhat-canada-gitops/catalog/sonarqube8/overlays/plugins?ref=master

resources:
  - workspace-pvc.yaml
  - secret.yaml
  - pipeline.yaml

# Generator options.
generatorOptions:
  labels:
    app: maven-settings
  disableNameSuffixHash: true

# Create a ConfigMap from custom settings.xml file.
configMapGenerator:
  - name: maven-settings-cm
    files:
      - settings.xml