apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: sample-app-pipeline-run
spec:
  pipelineRef:
    name: sample-app-pipeline
  params:
    - name: "namespace"
      value: "app"
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: workspace
    - name: maven-settings-cm
      configMap:
        name: maven-settings-cm