apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  labels:
    app: sample-app
    app.kubernetes.io/component: sample-app
    app.kubernetes.io/instance: sample-app
    app.kubernetes.io/part-of: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: sample-app
          image: image-registry.openshift-image-registry.svc:5000/app/sample-app:latest
          resources:
            limits:
              memory: 512Mi
              cpu: '1'
            requests:
              memory: 512Mi
              cpu: 250m
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
            - containerPort: 8778
              protocol: TCP