apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: sample-app
  labels:
    app: sample-app
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: sample-app
    weight: 100
  wildcardPolicy: None